### PR TITLE
CI: fix missing PYTHON var in meta.yml

### PR DESCRIPTION
**Pull request by mrakitin**
This PR is going to fix the missing `PYTHON` var, as `python` is not in the `host` section.

Symptoms:
```
conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for kazoo
INFO:conda_build.metadata:Attempting to finalize metadata for kazoo
Error: Failed to render jinja template in /root/kazoo-feedstock/recipe/meta.yaml:
'PYTHON' is undefined
```

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
It's passing now. Feel free to review/merge. Thanks!

**Comment by mrakitin** [comment]
attn @CJ-Wright

**Comment by CJ-Wright** [comment]
@conda-forge/kazoo

**Comment by StephenSorriaux** [comment]
Hi,

I am one of the Kazoo maintainer, how can I help with this PR to get our latest releases published?

**Comment by mrocklin** [comment]
Hello @StephenSorriaux , I'm adding you to the list of maintainers of this conda recipe in https://github.com/conda-forge/kazoo-feedstock/pull/6

**Comment by mrocklin** [comment]
Hrm, that PR also fails, presumably due to the same failure that this PR solves.

@CJ-Wright I'm not qualified to verify correctness of the changes here.  Currently there are no real maintainers of this feedstock.  What do you think is the best course of action here?  I'm inclined to blindly merge this and add @mrakitin and @StephanSiemen as maintainers.  Thoughts?

**Comment by mrakitin** [comment]
Hi @mrocklin, the only non-automatic change from me was fb8f056, and @CJ-Wright fixed the odd `build` section via 5518804. The rest is the automatic rerendering updates by conda-smithy. I am going to ask to rerender it again as there are new changes since July in conda-smithy.

NSLS-II feedstock for `kazoo` with the same updates is passing here: https://github.com/nsls-ii-forge/kazoo-feedstock/runs/232522160.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
Instead of #6, I can add @StephenSorriaux in the current PR branch. Thoughts?

**Comment by mrocklin** [comment]
Sounds good to me

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
OK, great! I added @StephenSorriaux & rerendered, so the username appears in the `.github/CODEOWNERS` file (and some other places). The build is passing.

Ready for final review/merge.

**Comment by StephenSorriaux** [comment]
Thank you @mrakitin @mrocklin

**Comment by CJ-Wright** [comment]
Lgtm

**Comment by mrocklin** [comment]
Thanks!

**Pull request merged**
